// <auto-generated />
using Examen2.Modelos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Examen2.Migrations
{
    [DbContext(typeof(CiudadanoDataContext))]
    [Migration("20200927032334_CrearDb")]
    partial class CrearDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Examen2.Modelos.Ciudad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripcion");

                    b.Property<string>("nombre_ciudad");

                    b.HasKey("id");

                    b.ToTable("Ciudads");
                });

            modelBuilder.Entity("Examen2.Modelos.Ciudadano", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ciudadid");

                    b.Property<string>("foto_ciudadano");

                    b.Property<string>("numero_telefono");

                    b.Property<string>("primer_apellido")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("primer_nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("segundo_apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("segundo_nombre")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("ciudadid");

                    b.ToTable("ciudadano","dbo");
                });

            modelBuilder.Entity("Examen2.Modelos.Ciudadano", b =>
                {
                    b.HasOne("Examen2.Modelos.Ciudad", "ciudad")
                        .WithMany("ciudadanos")
                        .HasForeignKey("ciudadid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
